name: Docker Image CI

on:
  workflow_dispatch:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: generate image tag
      run: |
        echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
        
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/pallanghunor/test-azure-webapp:$IMAGE_TAG --tag ghcr.io/pallanghunor/test-azure-webapp:latest
        docker login ghcr.io -u pallanghunor-p ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/pallanghunor/test-azure-webapp:$IMAGE_TAG
        docker push ghcr.io/pallanghunor/test-azure-webapp:latest
        
        
        
